In [1]:
import pandas as pd

In [2]:
train_no_anom = pd.read_csv("../data/01_raw/BATADAL_dataset03_train_no_anomaly.csv")
train_some_anom = pd.read_csv("../data/01_raw/BATADAL_dataset04_train_some_anomaly.csv")
test_with_anom = pd.read_csv("../data/01_raw/BATADAL_test_dataset_some_anomaly.csv")

In [3]:
# has leading white space
train_some_anom.columns = train_some_anom.columns.str.strip()

In [4]:
train_no_anom.shape, train_some_anom.shape, test_with_anom.shape

((8761, 45), (4177, 45), (2089, 44))

In [5]:
for i, _df in enumerate([train_no_anom, train_some_anom, test_with_anom]):
    for j, _df2 in enumerate([train_no_anom, train_some_anom, test_with_anom]):
        set1 = set(_df.columns.tolist())
        set2 = set(_df2.columns.tolist())
        
        print(i, j, len(set1 - set2))
        if len(set1 - set2) != 0:
            print("\t", set1-set2)

0 0 0
0 1 0
0 2 1
	 {'ATT_FLAG'}
1 0 0
1 1 0
1 2 1
	 {'ATT_FLAG'}
2 0 0
2 1 0
2 2 0

In [6]:
train_no_anom.columns

Index(['DATETIME', 'L_T1', 'L_T2', 'L_T3', 'L_T4', 'L_T5', 'L_T6', 'L_T7',
       'F_PU1', 'S_PU1', 'F_PU2', 'S_PU2', 'F_PU3', 'S_PU3', 'F_PU4', 'S_PU4',
       'F_PU5', 'S_PU5', 'F_PU6', 'S_PU6', 'F_PU7', 'S_PU7', 'F_PU8', 'S_PU8',
       'F_PU9', 'S_PU9', 'F_PU10', 'S_PU10', 'F_PU11', 'S_PU11', 'F_V2',
       'S_V2', 'P_J280', 'P_J269', 'P_J300', 'P_J256', 'P_J289', 'P_J415',
       'P_J302', 'P_J306', 'P_J307', 'P_J317', 'P_J14', 'P_J422', 'ATT_FLAG'],
      dtype='object')

# Train no anomaly

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
# !mkdir ../../GDN/data/batadal-slim-minmax
# 
output_dir = "../../GDN/data/batadal-slim-minmax"

In [10]:
SLIM = True

SENSOR_COLS = [c for c in train_no_anom.columns if c not in ["DATETIME", "ATT_FLAG"]]

DONT_USE = [c for c in SENSOR_COLS if "S_" in c]

if SLIM:
    SENSOR_COLS = [c for c in SENSOR_COLS if c not in DONT_USE]

SENSOR_COLS

['L_T1',
 'L_T2',
 'L_T3',
 'L_T4',
 'L_T5',
 'L_T6',
 'L_T7',
 'F_PU1',
 'F_PU2',
 'F_PU3',
 'F_PU4',
 'F_PU5',
 'F_PU6',
 'F_PU7',
 'F_PU8',
 'F_PU9',
 'F_PU10',
 'F_PU11',
 'F_V2',
 'P_J280',
 'P_J269',
 'P_J300',
 'P_J256',
 'P_J289',
 'P_J415',
 'P_J302',
 'P_J306',
 'P_J307',
 'P_J317',
 'P_J14',
 'P_J422']

In [11]:
normalizer = MinMaxScaler(feature_range=(0, 1)).fit(train_no_anom[SENSOR_COLS])

In [12]:
train_no_anom[SENSOR_COLS] = normalizer.transform(train_no_anom[SENSOR_COLS])

In [13]:
train_no_anom[SENSOR_COLS].describe()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,F_PU3,...,P_J300,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422
count,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.0,...,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000,8761.000000
mean,0.517838,0.557153,0.517209,0.582472,0.507047,0.808166,0.569895,0.414691,0.693668,0.0,...,0.543367,0.479956,0.542038,0.546550,0.448546,0.525037,0.450803,0.364733,0.344237,0.553736
std,0.264312,0.273490,0.266046,0.200725,0.256200,0.262749,0.210079,0.270048,0.421804,0.0,...,0.208677,0.282992,0.208074,0.146557,0.205125,0.324595,0.203737,0.119623,0.238618,0.207803
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.292347,0.342258,0.290391,0.423096,0.289343,0.627102,0.399670,0.237767,0.000000,0.0,...,0.458828,0.231394,0.457707,0.569495,0.265650,0.150474,0.269355,0.337682,0.170197,0.473960
50%,0.544633,0.596748,0.532353,0.584969,0.510529,1.000000,0.557264,0.301901,0.939430,0.0,...,0.569442,0.361859,0.567604,0.595029,0.379596,0.743630,0.381665,0.384637,0.257764,0.583523
75%,0.754662,0.796455,0.749302,0.746785,0.724573,1.000000,0.743314,0.720222,0.964790,0.0,...,0.679384,0.774597,0.677990,0.618411,0.634495,0.792366,0.635350,0.438852,0.591087,0.696201
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
# train_no_anom[SENSOR_COLS] = (train_no_anom[SENSOR_COLS] - train_no_anom[SENSOR_COLS].mean())/train_no_anom[SENSOR_COLS].std()

In [15]:
with open(f"{output_dir}/list.txt", "w") as f:
    f.writelines("\n".join(SENSOR_COLS))

In [16]:
train_no_anom.reset_index().rename(columns={"index": "timestamp"})[["timestamp" ]+ SENSOR_COLS].to_csv(f"{output_dir}/train.csv")

# Train with anomaly to use as test set

In [17]:
# from http://www.batadal.net/images/Attacks_TrainingDataset2.png
fmt ="%d/%m/%Y %H"
train_anomalies = [
    ("13/09/2016 23", "16/09/2016 00"),
    ("26/09/2016 11", "27/09/2016 10"),
    ("09/10/2016 09", "11/10/2016 20"),
    ("29/10/2016 19", "02/11/2016 16"),
    ("26/11/2016 17", "29/11/2016 04"),
    ("06/12/2016 07", "10/12/2016 04"),
    ("14/12/2016 15", "19/12/2016 04")
]

train_anomalies_dt = [
    (pd.to_datetime(s, format=fmt), pd.to_datetime(e, format=fmt)) for s, e in train_anomalies
]

In [18]:
train_anomalies_dt

[(Timestamp('2016-09-13 23:00:00'), Timestamp('2016-09-16 00:00:00')),
 (Timestamp('2016-09-26 11:00:00'), Timestamp('2016-09-27 10:00:00')),
 (Timestamp('2016-10-09 09:00:00'), Timestamp('2016-10-11 20:00:00')),
 (Timestamp('2016-10-29 19:00:00'), Timestamp('2016-11-02 16:00:00')),
 (Timestamp('2016-11-26 17:00:00'), Timestamp('2016-11-29 04:00:00')),
 (Timestamp('2016-12-06 07:00:00'), Timestamp('2016-12-10 04:00:00')),
 (Timestamp('2016-12-14 15:00:00'), Timestamp('2016-12-19 04:00:00'))]

In [19]:
train_some_anom = train_some_anom.reset_index().rename(columns={"index": "timestamp"})
train_some_anom["pdDateTime"] = pd.to_datetime(train_some_anom["DATETIME"], format="%d/%m/%y %H")
train_some_anom = train_some_anom.set_index(["pdDateTime"])

In [20]:
train_some_anom["attack"] = 0

In [21]:
for start, end in train_anomalies_dt:
    train_some_anom.loc[start:end, "attack"] = 1

In [22]:
train_some_anom["attack"].value_counts()

0    3685
1     492
Name: attack, dtype: int64

In [23]:
train_some_anom[SENSOR_COLS] = normalizer.transform(train_some_anom[SENSOR_COLS])

In [24]:
train_some_anom[SENSOR_COLS].describe()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,F_PU3,...,P_J300,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.0,...,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.524548,0.557566,0.518258,0.578047,0.507107,0.805195,0.575137,0.412354,0.692884,0.0,...,0.543093,0.479726,0.541754,0.545137,0.454170,0.525178,0.456303,0.367053,0.352708,0.553289
std,0.265781,0.273833,0.267178,0.202677,0.256422,0.262898,0.212432,0.274596,0.421217,0.0,...,0.210208,0.283438,0.209610,0.148015,0.218876,0.326084,0.217356,0.126590,0.259323,0.209451
min,-0.000025,0.003003,-0.001116,-0.030549,-0.004615,-0.080850,-0.158207,-1.251671,0.000000,0.0,...,-0.090598,0.033456,-0.094097,-0.015963,-0.041208,-0.008311,-0.041404,-0.006453,0.009602,-0.082090
25%,0.292205,0.345652,0.289060,0.419510,0.291606,0.615040,0.407005,0.233128,0.000000,0.0,...,0.457600,0.230769,0.457394,0.568474,0.265358,0.149848,0.268915,0.336821,0.171397,0.473741
50%,0.549279,0.595190,0.528259,0.575729,0.507673,1.000000,0.564149,0.299776,0.937282,0.0,...,0.572570,0.359525,0.569834,0.594453,0.388449,0.743432,0.390564,0.386502,0.259342,0.583187
75%,0.760212,0.798172,0.751773,0.743107,0.723739,1.000000,0.756777,0.716057,0.963744,0.0,...,0.682210,0.772880,0.679214,0.617698,0.640205,0.791595,0.640289,0.442029,0.596462,0.697324
max,1.188668,1.001154,0.998815,1.003472,0.999050,1.000000,1.000097,0.996355,0.997796,0.0,...,1.037777,0.996948,1.037951,1.039031,2.615700,1.202288,2.596771,0.944913,2.805221,1.040517

In [25]:
# train_some_anom[SENSOR_COLS] = (train_some_anom[SENSOR_COLS] - train_some_anom[SENSOR_COLS].mean())/train_some_anom[SENSOR_COLS].std()

In [26]:
train_some_anom[["timestamp"] + SENSOR_COLS + ["attack"]].to_csv(f"{output_dir}/train_some_anom.csv", index=False)

In [27]:
train_some_anom[SENSOR_COLS].describe()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,F_PU3,...,P_J300,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.0,...,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.524548,0.557566,0.518258,0.578047,0.507107,0.805195,0.575137,0.412354,0.692884,0.0,...,0.543093,0.479726,0.541754,0.545137,0.454170,0.525178,0.456303,0.367053,0.352708,0.553289
std,0.265781,0.273833,0.267178,0.202677,0.256422,0.262898,0.212432,0.274596,0.421217,0.0,...,0.210208,0.283438,0.209610,0.148015,0.218876,0.326084,0.217356,0.126590,0.259323,0.209451
min,-0.000025,0.003003,-0.001116,-0.030549,-0.004615,-0.080850,-0.158207,-1.251671,0.000000,0.0,...,-0.090598,0.033456,-0.094097,-0.015963,-0.041208,-0.008311,-0.041404,-0.006453,0.009602,-0.082090
25%,0.292205,0.345652,0.289060,0.419510,0.291606,0.615040,0.407005,0.233128,0.000000,0.0,...,0.457600,0.230769,0.457394,0.568474,0.265358,0.149848,0.268915,0.336821,0.171397,0.473741
50%,0.549279,0.595190,0.528259,0.575729,0.507673,1.000000,0.564149,0.299776,0.937282,0.0,...,0.572570,0.359525,0.569834,0.594453,0.388449,0.743432,0.390564,0.386502,0.259342,0.583187
75%,0.760212,0.798172,0.751773,0.743107,0.723739,1.000000,0.756777,0.716057,0.963744,0.0,...,0.682210,0.772880,0.679214,0.617698,0.640205,0.791595,0.640289,0.442029,0.596462,0.697324
max,1.188668,1.001154,0.998815,1.003472,0.999050,1.000000,1.000097,0.996355,0.997796,0.0,...,1.037777,0.996948,1.037951,1.039031,2.615700,1.202288,2.596771,0.944913,2.805221,1.040517

# Actual test set

In [28]:
# http://www.batadal.net/images/Attacks_TestDataset.png
test_anomalies = [
    ("16/01/2017 09", "19/01/2017 06"),
    ("30/01/2017 08", "02/02/2017 00"),
    ("09/02/2017 03", "10/02/2017 09"),
    ("12/02/2017 01", "13/02/2017 07"),
    ("24/02/2017 05", "28/02/2017 08"),
    ("10/03/2017 14", "13/03/2017 21"),
    ("25/03/2017 20", "27/03/2017 01")
]

test_anomalies_dt = [
    (pd.to_datetime(s, format=fmt), pd.to_datetime(e, format=fmt)) for s, e in test_anomalies
]

In [29]:
test_anomalies_dt

[(Timestamp('2017-01-16 09:00:00'), Timestamp('2017-01-19 06:00:00')),
 (Timestamp('2017-01-30 08:00:00'), Timestamp('2017-02-02 00:00:00')),
 (Timestamp('2017-02-09 03:00:00'), Timestamp('2017-02-10 09:00:00')),
 (Timestamp('2017-02-12 01:00:00'), Timestamp('2017-02-13 07:00:00')),
 (Timestamp('2017-02-24 05:00:00'), Timestamp('2017-02-28 08:00:00')),
 (Timestamp('2017-03-10 14:00:00'), Timestamp('2017-03-13 21:00:00')),
 (Timestamp('2017-03-25 20:00:00'), Timestamp('2017-03-27 01:00:00'))]

In [30]:
test_with_anom = test_with_anom.reset_index().rename(columns={"index": "timestamp"})
test_with_anom["pdDateTime"] = pd.to_datetime(test_with_anom["DATETIME"], format="%d/%m/%y %H")
test_with_anom = test_with_anom.set_index(["pdDateTime"])

In [31]:
test_with_anom["attack"] = 0
for start, end in test_anomalies_dt:
    test_with_anom.loc[start:end, "attack"] = 1

In [32]:
test_with_anom["attack"].value_counts()

0    1682
1     407
Name: attack, dtype: int64

In [33]:
test_with_anom[SENSOR_COLS] = normalizer.transform(test_with_anom[SENSOR_COLS])

In [34]:
test_with_anom[SENSOR_COLS].describe()

,L_T1,L_T2,L_T3,L_T4,L_T5,L_T6,L_T7,F_PU1,F_PU2,F_PU3,...,P_J300,P_J256,P_J289,P_J415,P_J302,P_J306,P_J307,P_J317,P_J14,P_J422
count,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,...,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000,2089.000000
mean,0.540369,0.569803,0.516075,0.583305,0.508725,0.814686,0.567939,0.396889,0.670055,2.749751,...,0.559841,0.480078,0.558619,0.549062,0.452783,0.522386,0.455531,0.363484,0.341773,0.568399
std,0.266218,0.268400,0.265536,0.202131,0.256790,0.255070,0.207407,0.328065,0.432525,16.072286,...,0.220657,0.290471,0.220141,0.149997,0.207967,0.325206,0.204953,0.120102,0.232625,0.209911
min,0.043920,0.003003,-0.001116,0.006646,0.012810,-0.006819,0.047094,-2.297614,0.000000,0.000000,...,-0.122576,0.009711,-0.126223,0.028183,-0.065827,0.012191,0.102279,-0.016345,0.010729,-0.114924
25%,0.318571,0.364274,0.285139,0.423230,0.291606,0.644652,0.394332,0.230978,0.000000,0.000000,...,0.472067,0.227759,0.471162,0.571599,0.275112,0.150173,0.279473,0.335697,0.177035,0.489376
50%,0.575646,0.613812,0.528259,0.586888,0.511158,1.000000,0.543872,0.296283,0.935883,0.000000,...,0.581707,0.358856,0.579778,0.595039,0.386127,0.742455,0.384137,0.384029,0.257087,0.597259
75%,0.771198,0.796310,0.751773,0.746826,0.730709,1.000000,0.744104,0.712026,0.962346,0.000000,...,0.691346,0.777562,0.690688,0.619651,0.635096,0.791595,0.635239,0.440455,0.561510,0.702797
max,1.322698,1.008603,0.998815,0.988594,0.995565,1.000000,0.995028,0.992861,0.998296,119.560000,...,1.713127,1.376526,1.716416,1.331640,1.032703,0.974487,1.032320,0.667057,1.052533,1.489247

In [35]:
# test_with_anom[SENSOR_COLS] = (test_with_anom[SENSOR_COLS] - test_with_anom[SENSOR_COLS].mean())/test_with_anom[SENSOR_COLS].std()

In [36]:
test_with_anom[["timestamp"] + SENSOR_COLS + ["attack"]].to_csv(f"{output_dir}/test_with_anom.csv", index=False)

# Make copy of test set we want to use

In [37]:
!cp {output_dir}/test_with_anom.csv {output_dir}/test.csv